# Generated by Django 3.0.4 on 2020-05-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookflixapp', '0002_autor_editorial_genero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='editorial',
            options={'verbose_name_plural': 'Editoriales'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name_plural': 'Generos'},
        ),
        migrations.AddField(
            model_name='autor',
            name='apellido',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
