# Generated by Django 3.0.4 on 2020-05-16 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookflixapp', '0002_auto_20200516_0416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='capitulo',
            options={'ordering': ['numero'], 'verbose_name_plural': 'Capitulos'},
        ),
        migrations.AlterModelOptions(
            name='editorial',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Editoriales'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Generos'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titulo'], 'verbose_name_plural': 'Libros'},
        ),
    ]
